/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BillboardRouteImport } from './routes/billboard'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiQuestionsRouteImport } from './routes/api/questions'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPeopleRouteImport } from './routes/api/people'
import { Route as ApiMomentsRouteImport } from './routes/api/moments'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDocumentsRouteImport } from './routes/api/documents'
import { Route as ApiDiscussionsRouteImport } from './routes/api/discussions'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as ApiAnswersRouteImport } from './routes/api/answers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMomentsRouteImport } from './routes/_app/moments'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDiscussionsRouteImport } from './routes/_app/discussions'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppConferencesIndexRouteImport } from './routes/_app/conferences/index'
import { Route as ApiMomentsSharedRouteImport } from './routes/api/moments/shared'
import { Route as ApiDocumentsIdRouteImport } from './routes/api/documents.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSessionsSlugRouteImport } from './routes/_app/sessions/$slug'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppProjectsSlugRouteImport } from './routes/_app/projects/$slug'
import { Route as AppPeopleUserIdRouteImport } from './routes/_app/people/$userId'
import { Route as AppDiscussionsIdRouteImport } from './routes/_app/discussions/$id'
import { Route as ApiQuestionsIdVoteRouteImport } from './routes/api/questions.$id.vote'
import { Route as ApiQuestionsIdPromoteRouteImport } from './routes/api/questions.$id.promote'
import { Route as ApiMeetupsIdRsvpRouteImport } from './routes/api/meetups.$id.rsvp'
import { Route as ApiDiscussionsIdPostsRouteImport } from './routes/api/discussions.$id.posts'
import { Route as AppProjectsSlugEditRouteImport } from './routes/_app/projects/$slug.edit'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BillboardRoute = BillboardRouteImport.update({
  id: '/billboard',
  path: '/billboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsRoute = ApiQuestionsRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeopleRoute = ApiPeopleRouteImport.update({
  id: '/api/people',
  path: '/api/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMomentsRoute = ApiMomentsRouteImport.update({
  id: '/api/moments',
  path: '/api/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsRoute = ApiDocumentsRouteImport.update({
  id: '/api/documents',
  path: '/api/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscussionsRoute = ApiDiscussionsRouteImport.update({
  id: '/api/discussions',
  path: '/api/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnswersRoute = ApiAnswersRouteImport.update({
  id: '/api/answers',
  path: '/api/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMomentsRoute = AppMomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsRoute = AppDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppConferencesIndexRoute = AppConferencesIndexRouteImport.update({
  id: '/conferences/',
  path: '/conferences/',
  getParentRoute: () => AppRoute,
} as any)
const ApiMomentsSharedRoute = ApiMomentsSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => ApiMomentsRoute,
} as any)
const ApiDocumentsIdRoute = ApiDocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDocumentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionsSlugRoute = AppSessionsSlugRouteImport.update({
  id: '/sessions/$slug',
  path: '/sessions/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleUserIdRoute = AppPeopleUserIdRouteImport.update({
  id: '/people/$userId',
  path: '/people/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsIdRoute = AppDiscussionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDiscussionsRoute,
} as any)
const ApiQuestionsIdVoteRoute = ApiQuestionsIdVoteRouteImport.update({
  id: '/$id/vote',
  path: '/$id/vote',
  getParentRoute: () => ApiQuestionsRoute,
} as any)
const ApiQuestionsIdPromoteRoute = ApiQuestionsIdPromoteRouteImport.update({
  id: '/$id/promote',
  path: '/$id/promote',
  getParentRoute: () => ApiQuestionsRoute,
} as any)
const ApiMeetupsIdRsvpRoute = ApiMeetupsIdRsvpRouteImport.update({
  id: '/api/meetups/$id/rsvp',
  path: '/api/meetups/$id/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscussionsIdPostsRoute = ApiDiscussionsIdPostsRouteImport.update({
  id: '/$id/posts',
  path: '/$id/posts',
  getParentRoute: () => ApiDiscussionsRoute,
} as any)
const AppProjectsSlugEditRoute = AppProjectsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/billboard': typeof BillboardRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/discussions': typeof AppDiscussionsRouteWithChildren
  '/messages': typeof AppMessagesRoute
  '/moments': typeof AppMomentsRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/api/answers': typeof ApiAnswersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/connections': typeof ApiConnectionsRoute
  '/api/discussions': typeof ApiDiscussionsRouteWithChildren
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/discussions/$id': typeof AppDiscussionsIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/projects/$slug': typeof AppProjectsSlugRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/sessions/$slug': typeof AppSessionsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/moments/shared': typeof ApiMomentsSharedRoute
  '/conferences/': typeof AppConferencesIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/projects/$slug/edit': typeof AppProjectsSlugEditRoute
  '/api/discussions/$id/posts': typeof ApiDiscussionsIdPostsRoute
  '/api/meetups/$id/rsvp': typeof ApiMeetupsIdRsvpRoute
  '/api/questions/$id/promote': typeof ApiQuestionsIdPromoteRoute
  '/api/questions/$id/vote': typeof ApiQuestionsIdVoteRoute
}
export interface FileRoutesByTo {
  '/billboard': typeof BillboardRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/discussions': typeof AppDiscussionsRouteWithChildren
  '/messages': typeof AppMessagesRoute
  '/moments': typeof AppMomentsRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/api/answers': typeof ApiAnswersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/connections': typeof ApiConnectionsRoute
  '/api/discussions': typeof ApiDiscussionsRouteWithChildren
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/': typeof AppIndexRoute
  '/discussions/$id': typeof AppDiscussionsIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/projects/$slug': typeof AppProjectsSlugRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/sessions/$slug': typeof AppSessionsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/moments/shared': typeof ApiMomentsSharedRoute
  '/conferences': typeof AppConferencesIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/projects/$slug/edit': typeof AppProjectsSlugEditRoute
  '/api/discussions/$id/posts': typeof ApiDiscussionsIdPostsRoute
  '/api/meetups/$id/rsvp': typeof ApiMeetupsIdRsvpRoute
  '/api/questions/$id/promote': typeof ApiQuestionsIdPromoteRoute
  '/api/questions/$id/vote': typeof ApiQuestionsIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/billboard': typeof BillboardRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/discussions': typeof AppDiscussionsRouteWithChildren
  '/_app/messages': typeof AppMessagesRoute
  '/_app/moments': typeof AppMomentsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/answers': typeof ApiAnswersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/connections': typeof ApiConnectionsRoute
  '/api/discussions': typeof ApiDiscussionsRouteWithChildren
  '/api/documents': typeof ApiDocumentsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/discussions/$id': typeof AppDiscussionsIdRoute
  '/_app/people/$userId': typeof AppPeopleUserIdRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/sessions/$slug': typeof AppSessionsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/$id': typeof ApiDocumentsIdRoute
  '/api/moments/shared': typeof ApiMomentsSharedRoute
  '/_app/conferences/': typeof AppConferencesIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/projects/$slug/edit': typeof AppProjectsSlugEditRoute
  '/api/discussions/$id/posts': typeof ApiDiscussionsIdPostsRoute
  '/api/meetups/$id/rsvp': typeof ApiMeetupsIdRsvpRoute
  '/api/questions/$id/promote': typeof ApiQuestionsIdPromoteRoute
  '/api/questions/$id/vote': typeof ApiQuestionsIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billboard'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/discussions'
    | '/messages'
    | '/moments'
    | '/profile'
    | '/search'
    | '/settings'
    | '/api/answers'
    | '/api/concierge'
    | '/api/connections'
    | '/api/discussions'
    | '/api/documents'
    | '/api/health'
    | '/api/messages'
    | '/api/moments'
    | '/api/people'
    | '/api/projects'
    | '/api/questions'
    | '/api/search'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/discussions/$id'
    | '/people/$userId'
    | '/projects/$slug'
    | '/projects/new'
    | '/sessions/$slug'
    | '/api/auth/$'
    | '/api/documents/$id'
    | '/api/moments/shared'
    | '/conferences/'
    | '/people/'
    | '/projects/'
    | '/sessions/'
    | '/projects/$slug/edit'
    | '/api/discussions/$id/posts'
    | '/api/meetups/$id/rsvp'
    | '/api/questions/$id/promote'
    | '/api/questions/$id/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billboard'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/discussions'
    | '/messages'
    | '/moments'
    | '/profile'
    | '/search'
    | '/settings'
    | '/api/answers'
    | '/api/concierge'
    | '/api/connections'
    | '/api/discussions'
    | '/api/documents'
    | '/api/health'
    | '/api/messages'
    | '/api/moments'
    | '/api/people'
    | '/api/projects'
    | '/api/questions'
    | '/api/search'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/'
    | '/discussions/$id'
    | '/people/$userId'
    | '/projects/$slug'
    | '/projects/new'
    | '/sessions/$slug'
    | '/api/auth/$'
    | '/api/documents/$id'
    | '/api/moments/shared'
    | '/conferences'
    | '/people'
    | '/projects'
    | '/sessions'
    | '/projects/$slug/edit'
    | '/api/discussions/$id/posts'
    | '/api/meetups/$id/rsvp'
    | '/api/questions/$id/promote'
    | '/api/questions/$id/vote'
  id:
    | '__root__'
    | '/_app'
    | '/billboard'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_app/discussions'
    | '/_app/messages'
    | '/_app/moments'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/settings'
    | '/api/answers'
    | '/api/concierge'
    | '/api/connections'
    | '/api/discussions'
    | '/api/documents'
    | '/api/health'
    | '/api/messages'
    | '/api/moments'
    | '/api/people'
    | '/api/projects'
    | '/api/questions'
    | '/api/search'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/_app/'
    | '/_app/discussions/$id'
    | '/_app/people/$userId'
    | '/_app/projects/$slug'
    | '/_app/projects/new'
    | '/_app/sessions/$slug'
    | '/api/auth/$'
    | '/api/documents/$id'
    | '/api/moments/shared'
    | '/_app/conferences/'
    | '/_app/people/'
    | '/_app/projects/'
    | '/_app/sessions/'
    | '/_app/projects/$slug/edit'
    | '/api/discussions/$id/posts'
    | '/api/meetups/$id/rsvp'
    | '/api/questions/$id/promote'
    | '/api/questions/$id/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  BillboardRoute: typeof BillboardRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAnswersRoute: typeof ApiAnswersRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  ApiConnectionsRoute: typeof ApiConnectionsRoute
  ApiDiscussionsRoute: typeof ApiDiscussionsRouteWithChildren
  ApiDocumentsRoute: typeof ApiDocumentsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiMomentsRoute: typeof ApiMomentsRouteWithChildren
  ApiPeopleRoute: typeof ApiPeopleRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiQuestionsRoute: typeof ApiQuestionsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMeetupsIdRsvpRoute: typeof ApiMeetupsIdRsvpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billboard': {
      id: '/billboard'
      path: '/billboard'
      fullPath: '/billboard'
      preLoaderRoute: typeof BillboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/people': {
      id: '/api/people'
      path: '/api/people'
      fullPath: '/api/people'
      preLoaderRoute: typeof ApiPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moments': {
      id: '/api/moments'
      path: '/api/moments'
      fullPath: '/api/moments'
      preLoaderRoute: typeof ApiMomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents': {
      id: '/api/documents'
      path: '/api/documents'
      fullPath: '/api/documents'
      preLoaderRoute: typeof ApiDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discussions': {
      id: '/api/discussions'
      path: '/api/discussions'
      fullPath: '/api/discussions'
      preLoaderRoute: typeof ApiDiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/answers': {
      id: '/api/answers'
      path: '/api/answers'
      fullPath: '/api/answers'
      preLoaderRoute: typeof ApiAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moments': {
      id: '/_app/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof AppMomentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions': {
      id: '/_app/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AppDiscussionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conferences/': {
      id: '/_app/conferences/'
      path: '/conferences'
      fullPath: '/conferences/'
      preLoaderRoute: typeof AppConferencesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/moments/shared': {
      id: '/api/moments/shared'
      path: '/shared'
      fullPath: '/api/moments/shared'
      preLoaderRoute: typeof ApiMomentsSharedRouteImport
      parentRoute: typeof ApiMomentsRoute
    }
    '/api/documents/$id': {
      id: '/api/documents/$id'
      path: '/$id'
      fullPath: '/api/documents/$id'
      preLoaderRoute: typeof ApiDocumentsIdRouteImport
      parentRoute: typeof ApiDocumentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sessions/$slug': {
      id: '/_app/sessions/$slug'
      path: '/sessions/$slug'
      fullPath: '/sessions/$slug'
      preLoaderRoute: typeof AppSessionsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$userId': {
      id: '/_app/people/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof AppPeopleUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions/$id': {
      id: '/_app/discussions/$id'
      path: '/$id'
      fullPath: '/discussions/$id'
      preLoaderRoute: typeof AppDiscussionsIdRouteImport
      parentRoute: typeof AppDiscussionsRoute
    }
    '/api/questions/$id/vote': {
      id: '/api/questions/$id/vote'
      path: '/$id/vote'
      fullPath: '/api/questions/$id/vote'
      preLoaderRoute: typeof ApiQuestionsIdVoteRouteImport
      parentRoute: typeof ApiQuestionsRoute
    }
    '/api/questions/$id/promote': {
      id: '/api/questions/$id/promote'
      path: '/$id/promote'
      fullPath: '/api/questions/$id/promote'
      preLoaderRoute: typeof ApiQuestionsIdPromoteRouteImport
      parentRoute: typeof ApiQuestionsRoute
    }
    '/api/meetups/$id/rsvp': {
      id: '/api/meetups/$id/rsvp'
      path: '/api/meetups/$id/rsvp'
      fullPath: '/api/meetups/$id/rsvp'
      preLoaderRoute: typeof ApiMeetupsIdRsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discussions/$id/posts': {
      id: '/api/discussions/$id/posts'
      path: '/$id/posts'
      fullPath: '/api/discussions/$id/posts'
      preLoaderRoute: typeof ApiDiscussionsIdPostsRouteImport
      parentRoute: typeof ApiDiscussionsRoute
    }
    '/_app/projects/$slug/edit': {
      id: '/_app/projects/$slug/edit'
      path: '/edit'
      fullPath: '/projects/$slug/edit'
      preLoaderRoute: typeof AppProjectsSlugEditRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
  }
}

interface AppDiscussionsRouteChildren {
  AppDiscussionsIdRoute: typeof AppDiscussionsIdRoute
}

const AppDiscussionsRouteChildren: AppDiscussionsRouteChildren = {
  AppDiscussionsIdRoute: AppDiscussionsIdRoute,
}

const AppDiscussionsRouteWithChildren = AppDiscussionsRoute._addFileChildren(
  AppDiscussionsRouteChildren,
)

interface AppProjectsSlugRouteChildren {
  AppProjectsSlugEditRoute: typeof AppProjectsSlugEditRoute
}

const AppProjectsSlugRouteChildren: AppProjectsSlugRouteChildren = {
  AppProjectsSlugEditRoute: AppProjectsSlugEditRoute,
}

const AppProjectsSlugRouteWithChildren = AppProjectsSlugRoute._addFileChildren(
  AppProjectsSlugRouteChildren,
)

interface AppRouteChildren {
  AppDiscussionsRoute: typeof AppDiscussionsRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppMomentsRoute: typeof AppMomentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeopleUserIdRoute: typeof AppPeopleUserIdRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppSessionsSlugRoute: typeof AppSessionsSlugRoute
  AppConferencesIndexRoute: typeof AppConferencesIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscussionsRoute: AppDiscussionsRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppMomentsRoute: AppMomentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeopleUserIdRoute: AppPeopleUserIdRoute,
  AppProjectsSlugRoute: AppProjectsSlugRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppSessionsSlugRoute: AppSessionsSlugRoute,
  AppConferencesIndexRoute: AppConferencesIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiDiscussionsRouteChildren {
  ApiDiscussionsIdPostsRoute: typeof ApiDiscussionsIdPostsRoute
}

const ApiDiscussionsRouteChildren: ApiDiscussionsRouteChildren = {
  ApiDiscussionsIdPostsRoute: ApiDiscussionsIdPostsRoute,
}

const ApiDiscussionsRouteWithChildren = ApiDiscussionsRoute._addFileChildren(
  ApiDiscussionsRouteChildren,
)

interface ApiDocumentsRouteChildren {
  ApiDocumentsIdRoute: typeof ApiDocumentsIdRoute
}

const ApiDocumentsRouteChildren: ApiDocumentsRouteChildren = {
  ApiDocumentsIdRoute: ApiDocumentsIdRoute,
}

const ApiDocumentsRouteWithChildren = ApiDocumentsRoute._addFileChildren(
  ApiDocumentsRouteChildren,
)

interface ApiMomentsRouteChildren {
  ApiMomentsSharedRoute: typeof ApiMomentsSharedRoute
}

const ApiMomentsRouteChildren: ApiMomentsRouteChildren = {
  ApiMomentsSharedRoute: ApiMomentsSharedRoute,
}

const ApiMomentsRouteWithChildren = ApiMomentsRoute._addFileChildren(
  ApiMomentsRouteChildren,
)

interface ApiQuestionsRouteChildren {
  ApiQuestionsIdPromoteRoute: typeof ApiQuestionsIdPromoteRoute
  ApiQuestionsIdVoteRoute: typeof ApiQuestionsIdVoteRoute
}

const ApiQuestionsRouteChildren: ApiQuestionsRouteChildren = {
  ApiQuestionsIdPromoteRoute: ApiQuestionsIdPromoteRoute,
  ApiQuestionsIdVoteRoute: ApiQuestionsIdVoteRoute,
}

const ApiQuestionsRouteWithChildren = ApiQuestionsRoute._addFileChildren(
  ApiQuestionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  BillboardRoute: BillboardRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAnswersRoute: ApiAnswersRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  ApiConnectionsRoute: ApiConnectionsRoute,
  ApiDiscussionsRoute: ApiDiscussionsRouteWithChildren,
  ApiDocumentsRoute: ApiDocumentsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiMomentsRoute: ApiMomentsRouteWithChildren,
  ApiPeopleRoute: ApiPeopleRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiQuestionsRoute: ApiQuestionsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMeetupsIdRsvpRoute: ApiMeetupsIdRsvpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
