/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPeopleRouteImport } from './routes/api/people'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppVenueRouteImport } from './routes/_app/venue'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDiscussionsRouteImport } from './routes/_app/discussions'
import { Route as AppConciergeRouteImport } from './routes/_app/concierge'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app/sessions/$sessionId'
import { Route as AppProjectsSlugRouteImport } from './routes/_app/projects/$slug'
import { Route as AppPeopleUserIdRouteImport } from './routes/_app/people/$userId'
import { Route as AppDiscussionsIdRouteImport } from './routes/_app/discussions/$id'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeopleRoute = ApiPeopleRouteImport.update({
  id: '/api/people',
  path: '/api/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVenueRoute = AppVenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsRoute = AppDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AppRoute,
} as any)
const AppConciergeRoute = AppConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleUserIdRoute = AppPeopleUserIdRouteImport.update({
  id: '/people/$userId',
  path: '/people/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsIdRoute = AppDiscussionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDiscussionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/concierge': typeof AppConciergeRoute
  '/discussions': typeof AppDiscussionsRouteWithChildren
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/venue': typeof AppVenueRoute
  '/api/health': typeof ApiHealthRoute
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/discussions/$id': typeof AppDiscussionsIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/people/': typeof AppPeopleIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/concierge': typeof AppConciergeRoute
  '/discussions': typeof AppDiscussionsRouteWithChildren
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/venue': typeof AppVenueRoute
  '/api/health': typeof ApiHealthRoute
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/': typeof AppIndexRoute
  '/discussions/$id': typeof AppDiscussionsIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/people': typeof AppPeopleIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/concierge': typeof AppConciergeRoute
  '/_app/discussions': typeof AppDiscussionsRouteWithChildren
  '/_app/messages': typeof AppMessagesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/venue': typeof AppVenueRoute
  '/api/health': typeof ApiHealthRoute
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/discussions/$id': typeof AppDiscussionsIdRoute
  '/_app/people/$userId': typeof AppPeopleUserIdRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/concierge'
    | '/discussions'
    | '/messages'
    | '/profile'
    | '/venue'
    | '/api/health'
    | '/api/people'
    | '/api/projects'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/discussions/$id'
    | '/people/$userId'
    | '/projects/$slug'
    | '/sessions/$sessionId'
    | '/api/auth/$'
    | '/people/'
    | '/projects/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/concierge'
    | '/discussions'
    | '/messages'
    | '/profile'
    | '/venue'
    | '/api/health'
    | '/api/people'
    | '/api/projects'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/'
    | '/discussions/$id'
    | '/people/$userId'
    | '/projects/$slug'
    | '/sessions/$sessionId'
    | '/api/auth/$'
    | '/people'
    | '/projects'
    | '/sessions'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_app/concierge'
    | '/_app/discussions'
    | '/_app/messages'
    | '/_app/profile'
    | '/_app/venue'
    | '/api/health'
    | '/api/people'
    | '/api/projects'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/_app/'
    | '/_app/discussions/$id'
    | '/_app/people/$userId'
    | '/_app/projects/$slug'
    | '/_app/sessions/$sessionId'
    | '/api/auth/$'
    | '/_app/people/'
    | '/_app/projects/'
    | '/_app/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPeopleRoute: typeof ApiPeopleRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/people': {
      id: '/api/people'
      path: '/api/people'
      fullPath: '/api/people'
      preLoaderRoute: typeof ApiPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/venue': {
      id: '/_app/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof AppVenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions': {
      id: '/_app/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AppDiscussionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/concierge': {
      id: '/_app/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof AppConciergeRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$userId': {
      id: '/_app/people/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof AppPeopleUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions/$id': {
      id: '/_app/discussions/$id'
      path: '/$id'
      fullPath: '/discussions/$id'
      preLoaderRoute: typeof AppDiscussionsIdRouteImport
      parentRoute: typeof AppDiscussionsRoute
    }
  }
}

interface AppDiscussionsRouteChildren {
  AppDiscussionsIdRoute: typeof AppDiscussionsIdRoute
}

const AppDiscussionsRouteChildren: AppDiscussionsRouteChildren = {
  AppDiscussionsIdRoute: AppDiscussionsIdRoute,
}

const AppDiscussionsRouteWithChildren = AppDiscussionsRoute._addFileChildren(
  AppDiscussionsRouteChildren,
)

interface AppRouteChildren {
  AppConciergeRoute: typeof AppConciergeRoute
  AppDiscussionsRoute: typeof AppDiscussionsRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppVenueRoute: typeof AppVenueRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeopleUserIdRoute: typeof AppPeopleUserIdRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConciergeRoute: AppConciergeRoute,
  AppDiscussionsRoute: AppDiscussionsRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppVenueRoute: AppVenueRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeopleUserIdRoute: AppPeopleUserIdRoute,
  AppProjectsSlugRoute: AppProjectsSlugRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPeopleRoute: ApiPeopleRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
