/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiQuestionsRouteImport } from './routes/api/questions'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiPeopleRouteImport } from './routes/api/people'
import { Route as ApiMomentsRouteImport } from './routes/api/moments'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiConnectionsRouteImport } from './routes/api/connections'
import { Route as ApiConciergeRouteImport } from './routes/api/concierge'
import { Route as ApiAnswersRouteImport } from './routes/api/answers'
import { Route as AppVenueRouteImport } from './routes/_app/venue'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDiscussionsRouteImport } from './routes/_app/discussions'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotwellKnownChar93OauthAuthorizationServerRouteImport } from './routes/[.well-known]/oauth-authorization-server'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as ApiMomentsSharedRouteImport } from './routes/api/moments/shared'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app/sessions/$sessionId'
import { Route as AppProjectsSlugRouteImport } from './routes/_app/projects/$slug'
import { Route as AppPeopleUserIdRouteImport } from './routes/_app/people/$userId'
import { Route as AppDiscussionsIdRouteImport } from './routes/_app/discussions/$id'
import { Route as ApiQuestionsIdVoteRouteImport } from './routes/api/questions.$id.vote'
import { Route as ApiQuestionsIdPromoteRouteImport } from './routes/api/questions.$id.promote'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsRoute = ApiQuestionsRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeopleRoute = ApiPeopleRouteImport.update({
  id: '/api/people',
  path: '/api/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMomentsRoute = ApiMomentsRouteImport.update({
  id: '/api/moments',
  path: '/api/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectionsRoute = ApiConnectionsRouteImport.update({
  id: '/api/connections',
  path: '/api/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConciergeRoute = ApiConciergeRouteImport.update({
  id: '/api/concierge',
  path: '/api/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnswersRoute = ApiAnswersRouteImport.update({
  id: '/api/answers',
  path: '/api/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVenueRoute = AppVenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsRoute = AppDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthAuthorizationServerRoute =
  Char91DotwellKnownChar93OauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const ApiMomentsSharedRoute = ApiMomentsSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => ApiMomentsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleUserIdRoute = AppPeopleUserIdRouteImport.update({
  id: '/people/$userId',
  path: '/people/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsIdRoute = AppDiscussionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDiscussionsRoute,
} as any)
const ApiQuestionsIdVoteRoute = ApiQuestionsIdVoteRouteImport.update({
  id: '/$id/vote',
  path: '/$id/vote',
  getParentRoute: () => ApiQuestionsRoute,
} as any)
const ApiQuestionsIdPromoteRoute = ApiQuestionsIdPromoteRouteImport.update({
  id: '/$id/promote',
  path: '/$id/promote',
  getParentRoute: () => ApiQuestionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/discussions': typeof AppDiscussionsRouteWithChildren
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/venue': typeof AppVenueRoute
  '/api/answers': typeof ApiAnswersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/connections': typeof ApiConnectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/discussions/$id': typeof AppDiscussionsIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/moments/shared': typeof ApiMomentsSharedRoute
  '/people/': typeof AppPeopleIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/api/questions/$id/promote': typeof ApiQuestionsIdPromoteRoute
  '/api/questions/$id/vote': typeof ApiQuestionsIdVoteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/discussions': typeof AppDiscussionsRouteWithChildren
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/venue': typeof AppVenueRoute
  '/api/answers': typeof ApiAnswersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/connections': typeof ApiConnectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/': typeof AppIndexRoute
  '/discussions/$id': typeof AppDiscussionsIdRoute
  '/people/$userId': typeof AppPeopleUserIdRoute
  '/projects/$slug': typeof AppProjectsSlugRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/moments/shared': typeof ApiMomentsSharedRoute
  '/people': typeof AppPeopleIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/api/questions/$id/promote': typeof ApiQuestionsIdPromoteRoute
  '/api/questions/$id/vote': typeof ApiQuestionsIdVoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-authorization-server': typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/discussions': typeof AppDiscussionsRouteWithChildren
  '/_app/messages': typeof AppMessagesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/venue': typeof AppVenueRoute
  '/api/answers': typeof ApiAnswersRoute
  '/api/concierge': typeof ApiConciergeRoute
  '/api/connections': typeof ApiConnectionsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/moments': typeof ApiMomentsRouteWithChildren
  '/api/people': typeof ApiPeopleRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tasks': typeof ApiTasksRoute
  '/_app/': typeof AppIndexRoute
  '/_app/discussions/$id': typeof AppDiscussionsIdRoute
  '/_app/people/$userId': typeof AppPeopleUserIdRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/moments/shared': typeof ApiMomentsSharedRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/api/questions/$id/promote': typeof ApiQuestionsIdPromoteRoute
  '/api/questions/$id/vote': typeof ApiQuestionsIdVoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/discussions'
    | '/messages'
    | '/profile'
    | '/search'
    | '/settings'
    | '/venue'
    | '/api/answers'
    | '/api/concierge'
    | '/api/connections'
    | '/api/health'
    | '/api/messages'
    | '/api/moments'
    | '/api/people'
    | '/api/projects'
    | '/api/questions'
    | '/api/search'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/discussions/$id'
    | '/people/$userId'
    | '/projects/$slug'
    | '/sessions/$sessionId'
    | '/api/auth/$'
    | '/api/moments/shared'
    | '/people/'
    | '/projects/'
    | '/sessions/'
    | '/api/questions/$id/promote'
    | '/api/questions/$id/vote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/discussions'
    | '/messages'
    | '/profile'
    | '/search'
    | '/settings'
    | '/venue'
    | '/api/answers'
    | '/api/concierge'
    | '/api/connections'
    | '/api/health'
    | '/api/messages'
    | '/api/moments'
    | '/api/people'
    | '/api/projects'
    | '/api/questions'
    | '/api/search'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/'
    | '/discussions/$id'
    | '/people/$userId'
    | '/projects/$slug'
    | '/sessions/$sessionId'
    | '/api/auth/$'
    | '/api/moments/shared'
    | '/people'
    | '/projects'
    | '/sessions'
    | '/api/questions/$id/promote'
    | '/api/questions/$id/vote'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/_app/discussions'
    | '/_app/messages'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/venue'
    | '/api/answers'
    | '/api/concierge'
    | '/api/connections'
    | '/api/health'
    | '/api/messages'
    | '/api/moments'
    | '/api/people'
    | '/api/projects'
    | '/api/questions'
    | '/api/search'
    | '/api/sessions'
    | '/api/stream'
    | '/api/tasks'
    | '/_app/'
    | '/_app/discussions/$id'
    | '/_app/people/$userId'
    | '/_app/projects/$slug'
    | '/_app/sessions/$sessionId'
    | '/api/auth/$'
    | '/api/moments/shared'
    | '/_app/people/'
    | '/_app/projects/'
    | '/_app/sessions/'
    | '/api/questions/$id/promote'
    | '/api/questions/$id/vote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthAuthorizationServerRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAnswersRoute: typeof ApiAnswersRoute
  ApiConciergeRoute: typeof ApiConciergeRoute
  ApiConnectionsRoute: typeof ApiConnectionsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiMomentsRoute: typeof ApiMomentsRouteWithChildren
  ApiPeopleRoute: typeof ApiPeopleRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiQuestionsRoute: typeof ApiQuestionsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTasksRoute: typeof ApiTasksRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/people': {
      id: '/api/people'
      path: '/api/people'
      fullPath: '/api/people'
      preLoaderRoute: typeof ApiPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/moments': {
      id: '/api/moments'
      path: '/api/moments'
      fullPath: '/api/moments'
      preLoaderRoute: typeof ApiMomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connections': {
      id: '/api/connections'
      path: '/api/connections'
      fullPath: '/api/connections'
      preLoaderRoute: typeof ApiConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/concierge': {
      id: '/api/concierge'
      path: '/api/concierge'
      fullPath: '/api/concierge'
      preLoaderRoute: typeof ApiConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/answers': {
      id: '/api/answers'
      path: '/api/answers'
      fullPath: '/api/answers'
      preLoaderRoute: typeof ApiAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/venue': {
      id: '/_app/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof AppVenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions': {
      id: '/_app/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AppDiscussionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/moments/shared': {
      id: '/api/moments/shared'
      path: '/shared'
      fullPath: '/api/moments/shared'
      preLoaderRoute: typeof ApiMomentsSharedRouteImport
      parentRoute: typeof ApiMomentsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$userId': {
      id: '/_app/people/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof AppPeopleUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions/$id': {
      id: '/_app/discussions/$id'
      path: '/$id'
      fullPath: '/discussions/$id'
      preLoaderRoute: typeof AppDiscussionsIdRouteImport
      parentRoute: typeof AppDiscussionsRoute
    }
    '/api/questions/$id/vote': {
      id: '/api/questions/$id/vote'
      path: '/$id/vote'
      fullPath: '/api/questions/$id/vote'
      preLoaderRoute: typeof ApiQuestionsIdVoteRouteImport
      parentRoute: typeof ApiQuestionsRoute
    }
    '/api/questions/$id/promote': {
      id: '/api/questions/$id/promote'
      path: '/$id/promote'
      fullPath: '/api/questions/$id/promote'
      preLoaderRoute: typeof ApiQuestionsIdPromoteRouteImport
      parentRoute: typeof ApiQuestionsRoute
    }
  }
}

interface AppDiscussionsRouteChildren {
  AppDiscussionsIdRoute: typeof AppDiscussionsIdRoute
}

const AppDiscussionsRouteChildren: AppDiscussionsRouteChildren = {
  AppDiscussionsIdRoute: AppDiscussionsIdRoute,
}

const AppDiscussionsRouteWithChildren = AppDiscussionsRoute._addFileChildren(
  AppDiscussionsRouteChildren,
)

interface AppRouteChildren {
  AppDiscussionsRoute: typeof AppDiscussionsRouteWithChildren
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVenueRoute: typeof AppVenueRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPeopleUserIdRoute: typeof AppPeopleUserIdRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscussionsRoute: AppDiscussionsRouteWithChildren,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVenueRoute: AppVenueRoute,
  AppIndexRoute: AppIndexRoute,
  AppPeopleUserIdRoute: AppPeopleUserIdRoute,
  AppProjectsSlugRoute: AppProjectsSlugRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiMomentsRouteChildren {
  ApiMomentsSharedRoute: typeof ApiMomentsSharedRoute
}

const ApiMomentsRouteChildren: ApiMomentsRouteChildren = {
  ApiMomentsSharedRoute: ApiMomentsSharedRoute,
}

const ApiMomentsRouteWithChildren = ApiMomentsRoute._addFileChildren(
  ApiMomentsRouteChildren,
)

interface ApiQuestionsRouteChildren {
  ApiQuestionsIdPromoteRoute: typeof ApiQuestionsIdPromoteRoute
  ApiQuestionsIdVoteRoute: typeof ApiQuestionsIdVoteRoute
}

const ApiQuestionsRouteChildren: ApiQuestionsRouteChildren = {
  ApiQuestionsIdPromoteRoute: ApiQuestionsIdPromoteRoute,
  ApiQuestionsIdVoteRoute: ApiQuestionsIdVoteRoute,
}

const ApiQuestionsRouteWithChildren = ApiQuestionsRoute._addFileChildren(
  ApiQuestionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthAuthorizationServerRoute:
    Char91DotwellKnownChar93OauthAuthorizationServerRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAnswersRoute: ApiAnswersRoute,
  ApiConciergeRoute: ApiConciergeRoute,
  ApiConnectionsRoute: ApiConnectionsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiMomentsRoute: ApiMomentsRouteWithChildren,
  ApiPeopleRoute: ApiPeopleRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiQuestionsRoute: ApiQuestionsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTasksRoute: ApiTasksRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
